### ISSUE TITLE
Form for leaving comments

### ISSUE THREAD

**Issue by faithghlee** [OpenArchitex/CherishCakes#67]
Under the current website, we do not have a form and potential customers have to send an email. Instead we could have a form  clients can leave queries and or feedback.

**Comment by SudharakaP** [comment]
- This from will have to take Name, Email, Phone Number (optional), Message. Also it should have a submit button and a cancel or reset button. 

- The name, email and message should not be empty. So when clicking submit it should do form validation for those fields.

**Comment by SudharakaP** [comment]
Also for handling the form and other information this is the goto place; https://www.gatsbyjs.org/docs/building-a-contact-form/

**Comment by SudharakaP** [comment]
Challenge here will be to find a way to send the emails in a reliable and cost efficient manner since we don't have a server. :smile:

**Comment by SudharakaP** [comment]
We'll close this for now since we are doing it at OpenLearnr (https://github.com/OpenArchitex/OpenLearnr/issues/391). But we'll revisit this when the client wants to have this here. :smile:
