### ISSUE TITLE
Add a Testimonial Section to the Homepage

### ISSUE THREAD

**Issue by SudharakaP** [OpenArchitex/CherishCakes#69]
We should add a testimonials section to the homepage. Maybe below the `Creative Designs` section we could add a `What Our Customers Say...` section. Similar to the changing jumbotron we can jump between customer reviews showing one review at a time. The customer name should also be shown with the review.

There's three reviews at the moment; 

1) Thank you soo much. The cake was soo good and it was the best of all! - by **Katuuo**

2) Priyanga... just want to say thank you very much for the gorgeous cake for my daughter!!! Everyone loved it and the cake was so delicious! Going to pass your name along to my friends if you don't mind! :smiley: - by **Julie**

3) Thank you for the beautiful cake Priyanga. It was delicious! :smiley: - by **Kavitha**

**Comment by SudharakaP** [comment]
@faithghlee : Thanks for working on this. Let me know if you have any questions. :+1:

**Comment by faithghlee** [comment]
Hi, maybe we can use this? https://gatsby-theme-testimonials.netlify.app/ -->

**Comment by SudharakaP** [comment]
> Hi, maybe we can use this? https://gatsby-theme-testimonials.netlify.app/ -->

This one is a bit of a overkill I think; since we already use react-bootstrap we can use [react-bootstrap components](https://react-bootstrap.github.io/components/alerts) to construct this. Also that one seems not to work properly in mobile screens. 

There's lot of examples on how it could be done using bootstrap; 

https://azmind.com/bootstrap-4-tutorial-one-page-website/#testimonials-section

https://www.uiuxstream.com/bootstrap-4-testimonial-slider-example/

https://www.webnots.com/bootstrap-testimonial-slider-widgets/

For some ideas on nice testimonial sections look at,

https://bashooka.com/inspiration/testimonial-ui-design-examples/
